### ISSUE TITLE
Can I use it in fragment?

### ISSUE THREAD

**Issue by zzMOM** [jdamcd/android-crop#100]
I use it in fragment. But it doesn't work. onActivityResult didn't called, after pick photo.

**Comment by askarsyzdykov** [comment]
you use a call from a fragment.startActivityForResult() or getActivity().startActivityForResult()?

**Comment by jdamcd** [comment]
This should work as long as you're passing the `Fragment` in `.start()`. This is available in the latest snapshot. Please re-open if you're doing that and you still see this issue.
