### ISSUE TITLE
Are you using android-crop in your app?

### ISSUE THREAD

**Issue by jdamcd** [jdamcd/android-crop#102]
I'd like to collect some more examples for the README. Please consider leaving a comment below and link to an app you've published that uses this library. Thanks!

**Comment by eclair4151** [comment]
This is an app i build for android that uses your library to crop photos
https://play.google.com/store/apps/details?id=com.yaptapapp.yaptap

**Comment by squeeish** [comment]
I'm using it, but my app isn't in production yet. Will update you again.

**Comment by dkozel** [comment]
We use it at Nameloop. I'm looking forward to using the circular guide. Thanks for the very useful library.
https://play.google.com/store/apps/details?id=com.nameloop.nameloop

**Comment by Pkmmte** [comment]
I'm using this awesome library for the NOWL app.
https://play.google.com/store/apps/details?id=co.nowl

**Comment by msealy** [comment]
Our team uses your library in our Bimoo app to crop profile photos. Thanks a bunch.
https://play.google.com/store/apps/details?id=com.rosemobility.bimoo

**Comment by vincenzoc** [comment]
I'm using it in my new app Yazzy Simulator:
https://play.google.com/store/apps/details?id=it.yazzy.simulator
Thank you

**Comment by AlexBalo** [comment]
We use you library in our recipes application for Android. Thank you for that!
Tasty Recipes: https://play.google.com/store/apps/details?id=com.appsfromthelocker.recipes&hl=en
