### ISSUE TITLE
Can't make it work in android.support.v4.app.Fragment

### ISSUE THREAD

**Issue by beraldofilippo** [jdamcd/android-crop#106]
Hi, following a recently closed issue, I want to point out that calling .start(Context c, Fragment f) is not possible if the hosting fragment is an instance of android.support.v4.app.Fragment.

Tried to cast it to a Fragment, but it is not possible to do it.
Thanks.

**Comment by jdamcd** [comment]
Are you using the latest snapshot version? The support `Fragment` version of `.start()` was added pretty recently. I'll do a proper release for that soon, just waiting on translations.

**Comment by beraldofilippo** [comment]
I'm currently using "compile 'com.soundcloud.android:android-crop:0.9.10@aar'" command in gradle.

I've partially come to a solution moving everything into the fragment's Activity and then calling a method of the fragment from the onActivityResult. I don't think taht can be an acceptable solution though.
I'll be waiting for the next release then.
Thank you.

**Comment by ChrisMCMine** [comment]
@beraldofilippo As a temporary workaround you could import the android-crop lib module as a module in your project and change [Crop.java#L4](https://github.com/jdamcd/android-crop/blob/master/lib/src/main/java/com/soundcloud/android/crop/Crop.java#L4) to ```android.support.v4.app.Fragment```

**Comment by jdamcd** [comment]
This is supported since 1.0.0, which is syncing to Maven central now.
