### ISSUE TITLE
where method Crop.of()

### ISSUE THREAD

**Issue by IP696** [jdamcd/android-crop#108]
`where method Crop.of() ??????????????

**Comment by metalurgus** [comment]
here it is    
https://github.com/jdamcd/android-crop/blob/master/lib/src/main/java/com/soundcloud/android/crop/Crop.java#L37

**Comment by lugeek** [comment]
I use this compile 'com.soundcloud.android:android-crop:0.9.10@aar' . And I don't have 'Crop.of()' method.

**Comment by mobamike** [comment]
I'm also using compile 'com.soundcloud.android:android-crop:0.9.10@aar'

The method Crop.of() is not there.

**Comment by jdamcd** [comment]
The documentation was updated but the release is not quite ready to publish yet. The old version of the api is: `new Crop(source).output(output)...`

**Comment by Sheikh-Aman** [comment]
Thanks!
Would be great if we could put it on the main page

**Comment by jdamcd** [comment]
I'm going to release today with the API update.

**Comment by jdamcd** [comment]
1.0.0 is syncing to Maven central now.

**Comment by rondelrosario** [comment]
Thanks for the update.
