### ISSUE TITLE
Why was change min SDK version to 14?

### ISSUE THREAD

**Issue by mariolope10** [jdamcd/android-crop#111]
Hello, I have a simple question, gingerbread does not support anymore? There is no explain for this. 

Thanx¡ Sorry for my Spanish.

**Comment by jdamcd** [comment]
Dropping support for Gingerbread simplified the library. It removed the need to maintain alternative cropping logic for before the bitmap region decoder was available. It's reached the point where the percentage of users < ICS is too low to justify the additional effort.

If you need to support Gingerbread, you can use version `0.9.10` or fork the project.
