### ISSUE TITLE
Usage with Camera Intent?

### ISSUE THREAD

**Issue by anupsarode** [jdamcd/android-crop#118]
Hello,

This library works great for ImagePicker. Does this work with Camera capture intent? If yes, are there any examples available?

Thanks in advance.

**Comment by mobamike** [comment]
If this is not a feature already it would be a great one.

**Comment by anupsarode** [comment]
I have tried the following code so far. The CropImageActivity doesn't show up when image is captured.

Intent intent = new Intent("android.media.action.IMAGE_CAPTURE");
startActivityForResult(intent, REQUEST_CAPTURE_PHOTO);

@Override
protected void onActivityResult(int requestCode, int resultCode, Intent result)
{
    if (requestCode == REQUEST_CAPTURE_PHOTO && resultCode == RESULT_OK) 
    {
        Uri inputUri = data.getData();
        File cropped = new File(Environment.getExternalStorageDirectory() + "/cropped");
        if (!cropped.exists()) 
        {
            cropped.mkdir();
        }
        Uri outputUri = Uri.fromFile(new File(cropped.getAbsolutePath() + "/" + new Date().getTime() + ".png"));
      
       Crop.of(inputUri, outputUri).asSquare().start(this);
    }
}

**Comment by jdamcd** [comment]
You can crop any local image if you have a `Uri`, so camera images are no different. Direct camera integration is beyond the scope of the library, but I'll try to add an example as part of https://github.com/jdamcd/android-crop/issues/103.

**Comment by sridharananthakrishnan** [comment]
Its possible crop camera image using SoundCloud/crop library ... I'll
forward you code how to do it using this library.

**Comment by anupsarode** [comment]
@jdamcd - Thanks!

@sridharananthakrishnan  - If you can help me with the code, that will be great. Thanks!

**Comment by sridharananthakrishnan** [comment]
@anupsarode 
Try like this after capturing the image using camera intent use onActivityResult() method to call the jdamcd/crop intent. Before calling the crop intent you should import the souncloud crop library into your project.

 /**
     * Receiving activity result method will be called after closing the camera
     */
    @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        if (resultCode != RESULT_OK)
            return;

        switch (requestCode) {
            case REQUEST_CODE_CAPTURE_IMAGE:
                // Send image taken from camera for cropping
                cropImage();
                break;

            case Crop.REQUEST_CROP:
                // Handle Cropped Image
                handleCrop(FileUri);

        }
    }

 /**
     * Helper Methods
     */

    public Uri getOutputMediaFileUri(int type) {
        return Uri.fromFile(getOutputMediaFile(type));
    }

    private void beginCrop(Uri source) {
        FileUri = getOutputMediaFileUri(MEDIA_TYPE_IMAGE);
        Uri outputUri = FileUri;
        new Crop(source).output(outputUri).withAspect(0,0).start(this);
    }

    private void handleCrop(Uri OutputUri) {
        Intent i = new Intent(this, ProcessActivity.class);
        i.putExtra("FilePath", OutputUri.getPath());
        startActivity(i);
    }

    // Crop and resize the image for profile
    private void cropImage() {
       beginCrop(mImageCaptureUri);
    }

Thanks..! :+1

**Comment by huteri** [comment]
Hi, it does not clear how to set up mImageCaptureUri, you also have to give an example how to start the intent

**Comment by colonP173** [comment]
Hello, using this library since long time and works great... But when it comes to the size of the image, the size gets increased and there is a significant difference when it comes to uploading the images to server.. Is there any way to limit the size? Thanks in advance
