### ISSUE TITLE
is it possible to handle the aspect ratio with seekbar ?

### ISSUE THREAD

**Issue by ashokstel** [jdamcd/android-crop#124]
Thanks for providing the library, but i have facing one problem applying the aspect ratio with seekbar progress .Its is most important for me .Please help me

**Comment by jdamcd** [comment]
Hi @ashokstel. This library only supports configuring aspect ratio up front. Unfortunately, changing this at crop time is out of scope for now. I'd suggest forking the library to add your aspect ratio controls.
