### ISSUE TITLE
how can i zoom the image/bitmap in center based on cropoverlayview frame?

### ISSUE THREAD

**Issue by tyson512** [jdamcd/android-crop#125]
Here i need to zoom in or out the image/bitmap in center imageview based on cropoverlayview frame. 
please help with some snippet.

**Comment by jdamcd** [comment]
Hi @tyson512. I'm not really sure what you mean. The image already zooms in and out based on the crop selection. This is the default behaviour. Any other zoom controls are beyond the scope of this library.
