### ISSUE TITLE
Failed to resolve: com.soundcloud.android:android-crop:1.0.0

### ISSUE THREAD

**Issue by gmunumel** [jdamcd/android-crop#129]
I'm trying to add the library to my android project. I added ` compile 'com.soundcloud.android:android-crop:1.0.0'` to my app.gradle file. But it fails with: 

```
Error:(27, 13) Failed to resolve: com.soundcloud.android:android-crop:1.0.0
<a href="openFile">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>
```

Any idea?

**Comment by jdamcd** [comment]
Are you using Maven Central?

**Comment by gmunumel** [comment]
I think yes. 

What I have done in Android Studio is:
1) Open project structure
2) In my app, add a dependency using `Library dependency`
3) Then look for `android-crop` and selected
4) It starts to run the grable build and then it shows the error.

**Comment by jdamcd** [comment]
In your root `build.gradle` do you have the following? 
```
allprojects {
    repositories {
        mavenCentral()
    }
}
```
The default might have changed to `jcenter()` but this lib is only distributed on Maven Central. You can change it or add both.

**Comment by gmunumel** [comment]
I have it like this but is not working:

```
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:1.2.3'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        jcenter()
        mavenCentral()
    }
}
```

**Comment by ireadfaces** [comment]
compile 'com.soundcloud.android:android-crop:1.0.0@aar' worked for me.

**Comment by slmyldz** [comment]
@gmunumel Sometimes  android studio couldn't install dependencies. When I got this problem , I use gradlew on console with assembleDebug.

**Comment by faisalawan** [comment]
@ireadfaces thanks a lot, that solved the problem for me as well.

**Comment by jdamcd** [comment]
Sounds like this is a build system issue rather than a problem with the dependency hosting? I'm going to close the ticket for now. I'm not sure whether or not the `@aar` is strictly necessary, but I'll check that next release.
