### ISSUE TITLE
After crop get result == null

### ISSUE THREAD

**Issue by helloJp** [jdamcd/android-crop#130]
When I crop some png Pictures, it may happen that onActivityResult result ==null. 
```
java.io.IOException: Image failed to decode using GIF decoder
at com.soundcloud.android.crop.CropImageActivity.decodeRegionCrop(CropImageActivity.java:316)
```

**Comment by jdamcd** [comment]
Looks like the image was actually a GIF? These aren't supported, but the library doesn't prevent you from trying to crop them right now.

**Comment by jdamcd** [comment]
I'm going to close as a duplicate of https://github.com/jdamcd/android-crop/issues/104. Please re-open if you disagree.
