### ISSUE TITLE
How to crop image capture from camera? 

### ISSUE THREAD

**Issue by shaileshmulange** [jdamcd/android-crop#132]
Can possible to use this code for crop image taken from a camera. I have tried for camera image, but it's return null pointer exception. i.e.  Caused by: java.lang.NullPointerException

**Comment by liemlyquan** [comment]
Yes, it can crop image from both camera and gallery. There are some problems with the orientation though.

**Comment by shaileshmulange** [comment]
If orientation issue is there then why occurs NullPointerException. Can you suggest me which change is necessary for avoid orientation issue?

**Comment by liemlyquan** [comment]
Orientation should not cause NullPointerException. Just use the code in the README
Crop.of(inputUri, outputUri).asSquare().start(activity)

Regarding the orientation. You may need this fix for later though. Have a look at #122

**Comment by shaileshmulange** [comment]
Hi I didn't have an orientation issue. I want crop image from a camera. can you provide me a proper solution for it?

**Comment by liemlyquan** [comment]
Did you test it on some other phones. I am having it on my Galaxy Note 4. The code in the README is quite sufficient, maybe I need to have a look at some codes to give you a more specific one : D

**Comment by shaileshmulange** [comment]
Hi, I have got the solution. I am unable to send uri to beginCrop(Crop.mImageCaptureUri); method using result.getData(); in onActivityResult method that's why I have sent direct file uri to this method i.e.
beginCrop(Crop.mImageCaptureUri);

**Comment by liemlyquan** [comment]
I use the direct file Uri too :+1:

**Comment by bernardomesk** [comment]
@liemlyquan Can you post here the code that you use form camera and crop? Thank you!

**Comment by liemlyquan** [comment]
My code is still kind of messy to post. But I can briefly describe how it work

Follow the instruction [here](http://developer.android.com/training/camera/photobasics.html) until **Save the full-size photo**. In this step, you should have a File photoFile, it can be converted and used as your Uri. In my case, I used it for both input and output

After taking camera finish, you add another crop intent using Crop.of(Uri.fromFile(photoFile), Uri.fromFile(photoFile)...... as in README. Then you can retrived the cropped image from photoFile

Hope this helps

**Comment by jdamcd** [comment]
Check out #118. Somebody posted some sample code in there. There is an issue to add something similar to the example project at #103. Hope this helps.

**Comment by shiweibsw** [comment]
Android 6.0 Can not find the camera
