### ISSUE TITLE
Change Button Style

### ISSUE THREAD

**Issue by sgurdag** [jdamcd/android-crop#139]
How to change ok and cancel buttons style?
Thanks.

**Comment by chihao12** [comment]
did you manage to change ? @sgurdag

**Comment by sgurdag** [comment]
yes i did, thanks for reply.

**Comment by TeodorKolev** [comment]
Hello I use this via https://github.com/jeduan/cordova-plugin-crop/blob/master/src/android/CropPlugin.java 
Am I able to change button style somehow from there?
