### ISSUE TITLE
No such file or directory exception

### ISSUE THREAD

**Issue by tigercbc** [jdamcd/android-crop#144]
I got images by using the camera, and saved in SD card. The Uri string is like 'file:///storage/emulated/0/1437469321272.jpg'. 

please help!

**Comment by jdamcd** [comment]
I'm afraid there isn't much I can do without a lot more detail. Please feel free to re-open the issue with a full stack trace. Are you able to access the image at that `Uri` otherwise? Is this a duplicate of https://github.com/jdamcd/android-crop/issues/79?
