### ISSUE TITLE
Crop.pickImage doesn't support v4 or standard fragment

### ISSUE THREAD

**Issue by XinyueZ** [jdamcd/android-crop#151]
Any change ?
getActivity() works in fragment but the callback goes only to onActivityResult of Activity not in fragment.

**Comment by brettwmc** [comment]
For fragments you need to change your .start from .start(context) to .start(context, fragment) as is shown below:

Crop.of(imageURI, outputURI).asSquare().start(getActivity(),FragmentName.this);

**Comment by luca992** [comment]
Thanks...this should probably be in the readme

**Comment by jdamcd** [comment]
There are no `Fragment` variants of `pickImage` on the builder right now, but there is a PR: https://github.com/jdamcd/android-crop/pull/158. It'll be supported in the next release.

**Comment by jdamcd** [comment]
This is fixed on `master`. It'll be in the next release.
