### ISSUE TITLE
 Could not find com.android.support:support-annotations:21.0.0.

### ISSUE THREAD

**Issue by enrichico** [jdamcd/android-crop#155]
Seems like there is a problem finding support-annotations:21.0.0.

* What went wrong:
A problem occurred configuring project ':example'.
> A problem occurred configuring project ':lib'.
   > Could not resolve all dependencies for configuration ':lib:_debugCompile'.
      > Could not find com.android.support:support-annotations:21.0.0.
        Searched in the following locations:
            https://repo1.maven.org/maven2/com/android/support/support-annotations/21.0.0/support-annotations-21.0.0.pom
            https://repo1.maven.org/maven2/com/android/support/support-annotations/21.0.0/support-annotations-21.0.0.jar
        Required by:
            com.soundcloud.android:lib:1.0.0
      > Could not find com.android.support:support-v4:21.0.3.
        Searched in the following locations:
            https://repo1.maven.org/maven2/com/android/support/support-v4/21.0.3/support-v4-21.0.3.pom
            https://repo1.maven.org/maven2/com/android/support/support-v4/21.0.3/support-v4-21.0.3.jar
        Required by:
            com.soundcloud.android:lib:1.0.0

**Comment by jdamcd** [comment]
I think you need to have the Android support repository installed via the SDK installer, since Google don't host these libraries on Maven central. Feel free to re-open if that doesn't work.
