### ISSUE TITLE
resultCode is always RESULT_CANCELLED onActivityResult()

### ISSUE THREAD

**Issue by HaiLe** [jdamcd/android-crop#157]
I trigger Android Crop activity by calling this in my fragment.

Crop.of(mCapturedImageURI, mOutputImageURI).asSquare().start(getActivity(), this);

When I receive the callback in onActivityResult, the resultCode is always 0 (RESULT_CANCELLED). 

@Override
    public void onActivityResult(int requestCode, int resultCode, Intent data) {
        //super.onActivityResult(requestCode, resultCode, data);

        //Logging.log(requestCode + " onActivityResult: "+ resultCode);

        Logging.log("Request code " + requestCode);
        Logging.log("Result code " + resultCode);

        if (resultCode == RESULT_OK && requestCode == Crop.REQUEST_CROP ) {
            Logging.log("Output image: " + mOutputImageURI);
            Logging.log("Data: " + data);
        }       
    }

Please help. Thanks!

**Comment by growingdever** [comment]
i have same problem

**Comment by growingdever** [comment]
did you create mOutputImageURI properly?

**Comment by jdamcd** [comment]
The only cases where you should see result `RESULT_CANCELLED` are if the user:
- presses "Cancel" instead of "Done"
- presses the back button

Is there an error returned if you call `Crop.getError(result)`?

**Comment by jdamcd** [comment]
I think this is fixed by #150, but please re-open if it still occurs in the next release.
