### ISSUE TITLE
Set maximum size in terms of storage

### ISSUE THREAD

**Issue by dhruvilbadani** [jdamcd/android-crop#159]
Is it possible to set the maximum size of the chosen image (i.e.set the maximum size of the original image picked, not the cropped image) in terms of bytes or kilobytes or megabytes or some other unit of digital information?

**Comment by jdamcd** [comment]
It's not supported right now. It sounds like it would be tricky, and possibly beyond the scope of this library, but I'd definitely be willing to look at a PR that adds this feature.
