### ISSUE TITLE
android: windowTranslucentStatus incompatibility

### ISSUE THREAD

**Issue by blipinsk** [jdamcd/android-crop#162]
If the `android: windowTranslucentStatus` is set to true for the application style (API >=19), `CANCEL` and `DONE` buttons hide under the translucent status bar.

![windowtranslucentstatus](https://cloud.githubusercontent.com/assets/6371716/9681718/95bf5e12-5300-11e5-8141-6e0c14926da5.png)

**Comment by jdamcd** [comment]
Thanks for the bug report. As a workaround, you can set `android:windowTranslucentStatus="false"` just for the `CropActivity`, but ideally the library should set this programatically.
