### ISSUE TITLE
Add documentation and instructions on how to use

### ISSUE THREAD

**Issue by funianrun** [jdamcd/android-crop#164]
I've used about 10 libraries so far and can usually understand the instructions.  This library does not explain how to use itself at all.  Like what do all the methods do? what is the 'activity' do we need to make a custom XML activity? how do you get an ImageURI for param? what is an output URI etc etc etc etc etc!!!

**Comment by jdamcd** [comment]
Thanks for the feedback. This has a lot of crossover with #103, so I added more detail on that ticket.
