### ISSUE TITLE
No such method error while using the new version

### ISSUE THREAD

**Issue by nejmaa** [jdamcd/android-crop#165]
First of all ,I am using a ChatSDK within my application that depends on the version 0.9.10 .
I have to implement a new functionality which is  cropping images. I have added to my dependencies the version 1.0.1  and imitate the example that you have published. I succeeded,but now, the chat sdk craches because of NoSuchMethod error. 
I have added force=true to the dependencies on the Gradle of the SDK but with no success.
Could you help me plz :)

**Comment by jdamcd** [comment]
I'm not sure if there is anything I can do here. It's probably worth raising the issue with the maintainer of the SDK.

**Comment by omarv5150** [comment]
Hey
