### ISSUE TITLE
how to get path after crop ?

### ISSUE THREAD

**Issue by renwfy** [jdamcd/android-crop#167]
how to get path after crop ?

Uri destination = Uri.fromFile(new File(getCacheDir(), "cropped"));
Crop.of(source, destination).asSquare().start(this);

the file path is corp pic path?

**Comment by nove1398** [comment]
Crop.getOutput(data); That gives you the Uri of the cropped photo.

**Comment by jdamcd** [comment]
When the crop area is selected, the output is saved to the destination `Uri` specified in the builder, so in your example it's the file "cropped" in your cache directory.
