### ISSUE TITLE
how to set the guides visible

### ISSUE THREAD

**Issue by Mickyxing** [jdamcd/android-crop#168]
I want  the crop activity to show the guides just like the example shows(the four line in the selected window) but  I cannot find where to set it.
![Image of Yaktocat](https://raw.githubusercontent.com/jdamcd/android-crop/master/screenshot.png)

**Comment by jdamcd** [comment]
There are some attributes for customising the crop screen. Example [here](https://github.com/jdamcd/android-crop/blob/master/example/src/main/res/values/theme.xml). I've updated the README with this link.
