### ISSUE TITLE
Getting 404 as result code

### ISSUE THREAD

**Issue by amitclickapps** [jdamcd/android-crop#173]
On Nexus 5 Android version 6.0 some thing we got Result code 404.

**Comment by nove1398** [comment]
I am getting this error on a KitKat device as well

**Comment by jdamcd** [comment]
That simply means the image crop failed. That can happen for any number of reasons. Check out the [error handling](https://github.com/jdamcd/android-crop/blob/master/example/src/main/java/com/soundcloud/android/crop/example/MainActivity.java#L60) in the example project.
