### ISSUE TITLE
How can i use it inside a fragment?

### ISSUE THREAD

**Issue by arshadkazmi42** [jdamcd/android-crop#182]
I am invoking crop activity like this
Crop.pickImage(getActivity());
from inside a fragment on button click.
But its not going to onActivityResult in fragment. How can I integrate this crop feature inside a fragment?

**Comment by jdamcd** [comment]
If you're using the library from a `Fragment`, you can use the alternative methods: `Crop.pickImage(context, fragment)` and `Crop.of(in, out).start(context, fragment)`. There is JavaDoc on the [Crop](https://github.com/jdamcd/android-crop/blob/master/lib/src/main/java/com/soundcloud/android/crop/Crop.java) class for more details.
