### ISSUE TITLE
Is Library Updated with Rotate issue resolved?

### ISSUE THREAD

**Issue by arshadkazmi42** [jdamcd/android-crop#185]
Is the library updated with resolved Rotate issue? So I can just get the new library and integrate it in my app

**Comment by damonbakker** [comment]
I just noticed it when i integrated it in my app.
It's still there, rotate functionality would definitely be nice.

**Comment by jdamcd** [comment]
The changelog is here: https://github.com/jdamcd/android-crop/blob/master/CHANGELOG.md

The issue referenced is already tracked in several tickets: #140, #117, #46. There are some attempts to fix it in the PRs but nothing has been merged yet.
