### ISSUE TITLE
java.io.FileNotFoundException:

### ISSUE THREAD

**Issue by ForgetV** [jdamcd/android-crop#186]
When I try to crop local image,I get this exception.the uri which I use is like:
/storage/emulated/0/DCIM/Camera/1444104156743.jpg
Exception:
 Error reading image: No content provider: /storage/emulated/0/DCIM/Camera/1444104156743.jpg
                                                                   java.io.FileNotFoundException: No content provider: /storage/emulated/0/DCIM/Camera/1444104156743.jpg

**Comment by ForgetV** [comment]
The uri should be like this "file://"+/storage/emulated/0/DCIM/Camera/1444104156743.jpg

**Comment by jay006** [comment]
Thank you , @ForgetV  it worked...you saved my day
