### ISSUE TITLE
grow the cropping rectangle 

### ISSUE THREAD

**Issue by hpfs0** [jdamcd/android-crop#191]
when I  grow the cropping rectangle. The cropping rectangle width and height are modified at the same time. How I can modify width or height only?

**Comment by alex-shpak** [comment]
If you have set `withAspect` or `asSquare` cropping rectangle will be changed to follow these settings. 

If aspect ratio is not set - it works for me (tested on Nexus 5, SG S3 mini, LG G2 mini)
You can drag one of sides of cropping rectangle to change it or corner to change both.

**Comment by zelin** [comment]
Is there any way to set the Cropping Square to full image size by default in asSquare so initially it selects the max image u can select as square?

**Comment by jdamcd** [comment]
Yep. The width and height only change together to maintain a requested aspect ratio, which can be configured or not set.

**Comment by PriyankPainter** [comment]
How can i use width and height of crop area independently?
