### ISSUE TITLE
How to set HandleMode

### ISSUE THREAD

**Issue by MartinPetrulak** [jdamcd/android-crop#192]
Hello,
 i would like to set HandleMode to "Always" and would like to see something like this:
https://github.com/jdamcd/android-crop/blob/master/screenshot.png?raw=true
when user picks image, so he will know that image can be resized.
Thanks
Martin

**Comment by bafitor** [comment]
Anyone can help with this? 

Thanks

**Comment by MartinPetrulak** [comment]
Why do you show this screenshot in project if its not possible to achieve this "look" of cropper ???

**Comment by MartinPetrulak** [comment]
so i "fixed" this by not using this library... i started using https://github.com/edmodo/cropper for croping.

**Comment by jdamcd** [comment]
This can be configured via theme attributes. See the [example project](https://github.com/jdamcd/android-crop/blob/master/example/src/main/res/values/theme.xml).
