### ISSUE TITLE
Increasing image size drastically

### ISSUE THREAD

**Issue by harshtyagi7** [jdamcd/android-crop#195]
A 5m7.b file(2368x3200) was cropped and output was a 22mb file

**Comment by jdamcd** [comment]
Could you provide more details about the input file format and size (in pixels) of the output image?

**Comment by harshtyagi7** [comment]
The bug was due to my incorrect implementation. I had bypassed the resizing code that caused the bug. Closing the issue.

**Comment by jdamcd** [comment]
Cool. Thanks for the update.
