### ISSUE TITLE
can't use in fragment

### ISSUE THREAD

**Issue by soenaingtun** [jdamcd/android-crop#196]
It's okay in Activity , but when I'm trying with Fragment, just pick photo from gallery then doesn't know onActivityResult()..I can only pick from gallery, doesn't get anymore..

**Comment by soenaingtun** [comment]
sorry I get it, need to pass fragment argument

**Comment by shajishibili** [comment]
hey, can you please explain how you did it?

**Comment by soenaingtun** [comment]
just need to add fragment like that...

Crop.pickImage(getActivity(), yourfragment);


Crop.of(inputUri, outputUri).asSquare().start(getActivity(), yourfragment);

**Comment by jdamcd** [comment]
Looks like this was resolved.
