### ISSUE TITLE
Crop area not visible, problem discover on One+ One

### ISSUE THREAD

**Issue by Spierki** [jdamcd/android-crop#197]
I'm using this library to directly cropped a phone picture.

    if(requestCode == 1) {
            Uri destination = Uri.fromFile(new File(getCacheDir(), "cropped"));
            if(data != null)
                Crop.of(data.getData(), destination).asSquare().start(this, 4);
    }

I tried my code on a Sony xperia z3 and it's working fine. 
But it's seems that on a One+ One the crop area doesn't appear even if data (which represent the picture just taken) isn't null.

Have you ever seen this problem ?

**Comment by saintjab** [comment]
@Spierki, did you ever got it to work? Up to now, neither selecting image nor taking picture shows the crop area for me. I have tried everything.

**Comment by Spierki** [comment]
@saintjab Sorry to answer very late, did you find a way ? I my case, I used an other library, but I had a problem with the other too and maybe your problem could be the same. 

With the other library my image was dark because it was too big, the log was telling : 
OpenGLRenderer: Bitmap too large to be uploaded into a texture

I had to resize the image to display, maybe this is the same problem and that's why the image isn't rendering. Let me know if you try !

**Comment by jdamcd** [comment]
What's the size/format of the input image? It could definitely be an issue with loading very large images.

**Comment by saintjab** [comment]
Hi guys, you are all right. The image was too big but once I was able to resize, it worked perfectly. Thanks for getting back. Cheers. 

    On Friday, May 27, 2016 7:44 PM, Jamie McDonald <notifications@github.com> wrote:
 

 What's the size/format of the input image? It could definitely be an issue with loading very large images.—
