### ISSUE TITLE
Set cropped image as bitmap

### ISSUE THREAD

**Issue by power7714** [jdamcd/android-crop#200]
How would I set the cropped image as a bitmap to use as a texture for a 3d model?

**Comment by jdamcd** [comment]
This is a beyond the scope of the library, which is only concerned with cropping and saving images. After the cropped image is saved, you could decode it as a `Bitmap` with the output URI. See for e.g.: http://stackoverflow.com/questions/16804404/create-a-bitmap-drawable-from-file-path
