### ISSUE TITLE
Working with Bitmap instead of Uri

### ISSUE THREAD

**Issue by LucasEduardo** [jdamcd/android-crop#202]
Hello. Is there a way to work with Bitmap only, avoiding the Uri types on Crop.of()? I really don't wanna save the files in SD card, for my application I'm only using the images in memory. I should not use WRITE_EXTERNAL_STORAGE in my application as well.

**Comment by alex-shpak** [comment]
Hi.
I don't think that it's supported by library. But I would strongly recommend you to not work with big images, like photos, in memory only. On low-end or old devices it might cause out of memory errors or freezes.

**Comment by LucasEduardo** [comment]
I appreciate the recommendation. But I still think the lib should provide both ways to do that (with Uri and in memory only, using Bitmap). I don't wanna my app to have the permission to write external and the user has a very good/new device. It won't be for sale on play store.

**Comment by jdamcd** [comment]
Unfortunately this is beyond the scope of the library. Returning a large bitmap from the separate crop `Activity` is only practical by saving it to a file.
