### ISSUE TITLE
use in min sdk 9

### ISSUE THREAD

**Issue by Mahdiazadbar** [jdamcd/android-crop#203]
i cant use this in min sdk 9. they say min sdk is 9. how can i use in min sdk 9?

**Comment by alex-shpak** [comment]
According to changelog: https://github.com/jdamcd/android-crop/blob/master/CHANGELOG.md
Support of SDK level 9 was dropped in version 1.0.0 currently supports starts with SDK level 10

**Comment by jdamcd** [comment]
Yep. Min SDK is 10, as documented in the [README](https://github.com/jdamcd/android-crop/blob/master/README.md).
