### ISSUE TITLE
How to save cropped image

### ISSUE THREAD

**Issue by AbhayAnand** [jdamcd/android-crop#207]
This is very good for cropping but how to save cropped image. when i saved cropped image from bitmap. whole screen is being save. I am not getting scale size of image.

**Comment by Jai-GAY** [comment]
you may like to [reference here](http://www.cs.dartmouth.edu/~campbell/cs65/lecture14/lecture14.html).

**Comment by jdamcd** [comment]
The cropped selection is saved to the provided output URI when you press "done". Closing pending more detailed problem description.
