### ISSUE TITLE
onActivityResult not called

### ISSUE THREAD

**Issue by aresares** [jdamcd/android-crop#213]
Hi i'm using your lib in an Fragment but when the lib save the corped image it don't call onActivityResult

**Comment by imcbv** [comment]
Hi @aresares, 

if you're calling the function inside a fragment, be sure to use something like
`Crop.of(inputUri, inputUri).start(getContext(), this);`
or to handle onActivityResult in your MainActivity

**Comment by aresares** [comment]
thx it worked
