### ISSUE TITLE
No content provider

### ISSUE THREAD

**Issue by saintjab** [jdamcd/android-crop#214]
I am trying to capture image and then starting the CropActivity. The image gets captured but after tapping OK for the captured image, I always get this error. What am I doing wrong?
Error reading image: No content provider: /storage/emulated/0/image220.jpg
                                                                            java.io.FileNotFoundException: No content provider:

**Comment by jdamcd** [comment]
Did you try your code on a real device? Maybe this is related to your emulator setup.
