### ISSUE TITLE
Possibility to send cropped image result to server as png?

### ISSUE THREAD

**Issue by power7714** [jdamcd/android-crop#227]
I noticed that the cropped image result can be seen as a string like this file:///data/data/com.myapp.test/cache/cropped but doesn't have a file/format extension. How, if possible, can I retrieve that image for uploading to a server?

**Comment by Lawgrin** [comment]
@power7714 How do you need to upload it? standard file or base64 string?

**Comment by Lawgrin** [comment]
@power7714 We create a tempFile `tempFile = File.createTempFile("image", ".jpg", null);` then we use a FileOutputStream stream to write the image bytes to that file. then pass that file

**Comment by power7714** [comment]
I need to upload it as a PNG file. If it's possible

**Comment by Lawgrin** [comment]
just decode it to png and make the temp file a png

**Comment by pramjeet** [comment]
just make a bitmap and make a png temp file from it.

`Bitmap bitmap = MediaStore.Images.Media.getBitmap(this.getContentResolver(), imageURI);`
`bitmap.compress(Bitmap.CompressFormat.PNG, 100, yourPngFile);`

**Comment by power7714** [comment]
Does anyone have a better example/representation? I'm currently using this with Volley and getting a null error when trying to upload.

`	private void handleCrop(int resultCode, Intent result) {
			if (resultCode == RESULT_OK) {
				Uri imageUri = Crop.getOutput(result);
				try {
					bitmap = MediaStore.Images.Media.getBitmap(getContentResolver(), imageUri);
					//bitmap.compress()
				} catch (IOException e) {
					e.printStackTrace();
				}
				resultView.setImageBitmap(bitmap);

				saveDrawable();
				Toast.makeText(this, Crop.getOutput(result).toString(), Toast.LENGTH_LONG).show();
				Log.d("Result:", Crop.getOutput(result).toString());
			} else if (resultCode == Crop.RESULT_ERROR) {
				Toast.makeText(this, Crop.getError(result).getMessage(), Toast.LENGTH_SHORT).show();
			}
		}`

Then I'm using this to convert the bitmap to a base64 string:

`	public String getStringImage(Bitmap bmp){
			ByteArrayOutputStream baos = new ByteArrayOutputStream();
			bmp.compress(Bitmap.CompressFormat.PNG, 100, baos);
			byte[] imageBytes = baos.toByteArray();
			String encodedImage = Base64.encodeToString(imageBytes, Base64.DEFAULT);
			return encodedImage;
		}`

Any help would be much appreciated.

**Comment by jdamcd** [comment]
This is beyond of the scope of the library. I think it would make sense add a compression format option (PNG/JPG), but this isn't the best place to discuss whatever you do with the cropped image once it's saved.
