### ISSUE TITLE
withMaxSize(x,y) not working

### ISSUE THREAD

**Issue by bbdlg** [jdamcd/android-crop#27]
First, thank you for your perfect code : )
I want to crop image to 300*300 on android 4.1.2 ,  and my code like this:
	new Crop(inputUri).output(outputUri).withMaxSize(300, 300).asSquare().start(mActivity);
But I found it does not work.
So I rewrite some code in the library's source code.

In line：339 
      croppedImage = decoder.decodeRegion(rect, new BitmapFactory.Options());
changed to 
     Options options = new BitmapFactory.Options();
            	options.inSampleSize = width / maxX;
            	if(options.inSampleSize <= 0) {
            		options.inSampleSize = 1;
            	}
    croppedImage = decoder.decodeRegion(rect, options);

Finally, thanks again.

**Comment by squeeish** [comment]
Not working on Lollipop too.

**Comment by jdamcd** [comment]
It now resizes after `decodeRegionCrop()` if you supply max size params. I'll try and do a release fairly soon.
