### ISSUE TITLE
CropActivity empty on Samsung device

### ISSUE THREAD

**Issue by ghost** [jdamcd/android-crop#29]
Hi,
Your Library works perfectly with all device, except Samsung device (I tried on S2 and Note 2). That's really urgent, may be you have some workaround,  I can not find where does the problem?
![sc20140711-120218](https://cloud.githubusercontent.com/assets/3418677/3551228/b5624e7c-08e3-11e4-9b11-eebc8083c56f.jpeg)

Thanks for your job

**Comment by trustratch** [comment]
This issue still occurs on Samsung galaxy s5 android 5.0 with the latest version of the library, please re-opem this issue
