### ISSUE TITLE
Current .start(Activity activity) functionality is limiting.

### ISSUE THREAD

**Issue by zsperske** [jdamcd/android-crop#37]
Only allowing the crop activity to be started via an activity is a bit restrictive, I'm trying to deliver my result to a fragment's onActivityResult instead of an activity and also add some extras to the intent that is returned. I know this is vague but some more control over launching the activity/returning a result would be very helpful.

**Comment by axelfran** [comment]
Hi,

Has there been any progress on this?

**Comment by jdamcd** [comment]
@axelfran Yep. This is fixed since at least 1.0.0.

**Comment by axelfran** [comment]
Thanks, @jdamcd! :)
