### ISSUE TITLE
Get the picture quality is poor。

### ISSUE THREAD

**Issue by guoGavin** [jdamcd/android-crop#58]
First,this issue still exists it seems
https://github.com/jdamcd/android-crop/issues/27
so，I made the following changes in CropImageActivity.java：
1. IN_MEMORY_CROP = Build.VERSION.SDK_INT > Build.VERSION_CODES.GINGERBREAD_MR1;
not '<'.
2.// RectF dstRect = new RectF(0, 0, width, height);
   RectF dstRect = new RectF(0, 0, outWidth, outHeight);
If a high-resolution picture itself,and of high quality(maybe 4~5M),After cutting,get the picture quality is poor.

**Comment by xxxifan** [comment]
not working for me , get a weird picture
