### ISSUE TITLE
Please update aar

### ISSUE THREAD

**Issue by crossle** [jdamcd/android-crop#69]

**Comment by amouly** [comment]
+1

**Comment by cbhill** [comment]
+1

**Comment by jdamcd** [comment]
I want to push a release soon, but not before it's ready. Next Friday maybe.

**Comment by danielwilson1702** [comment]
+1, my withMaxSize() property doesn't seem to work, and I believe the a new release should fix it based on #26

**Comment by akohout** [comment]
Any news here @jdamcd ?

**Comment by suciudaniel** [comment]
+1
