### ISSUE TITLE
Crop is returning resultCode 0

### ISSUE THREAD

**Issue by mauriciogior** [jdamcd/android-crop#80]
Why `new Crop(...)...start()` is not returning `Activity.RESULT_OK` when the crop was successful?

**Comment by jdamcd** [comment]
I can't reproduce this issue. You get a cancelled result after pressing "Done"?

Feel free to re-open the issue if you can provide reproduction steps.

**Comment by imackinn** [comment]
@mauriciogior I had this issue too, but I suspect it was caused by me passing in a null output uri to the Crop object. It has to point to an open file for it not to return resultCode 0

**Comment by davidgoli** [comment]
I just had ran into this same thing, would be nice if it were mentioned in the docs
