### ISSUE TITLE
i18n resource dir not found in maven central aar

### ISSUE THREAD

**Issue by longkai** [jdamcd/android-crop#90]
![image](https://cloud.githubusercontent.com/assets/1432582/6459471/d95d05de-c1c9-11e4-9f6a-7b7ad1c30a66.png)

As the image shows, there is no i18n resource dir, but I did found there are i18n resource dirs in the source code.

**Comment by jdamcd** [comment]
Coming soon. I haven't cut a release since the translations were contributed, but I'm working towards that as time permits.
