### ISSUE TITLE
onActivityResult() never called (Samsung Galaxy S4)

### ISSUE THREAD

**Issue by androidvaler** [jdamcd/android-crop#94]
Hello,

onActivityResult() method never called on my Samsung Galaxy S4 (Android 4.2.2) after crop or after cancel crop.

**Comment by androidvaler** [comment]
I found problem. It was my bug with a calling startActivityForResult() method in Fragment.
http://stackoverflow.com/a/11011686/1225669

Sorry.

**Comment by Anawaz** [comment]
there should be a method which start cropping with fragment object.
